### ISSUE TITLE
Fix identifier of test letter example

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/scholarly-web-annotation-client#9]
The test letter example has no identifier for the element that the annotation client gets attached to.

**Comment by marijnkoolen** [comment]
Should be fixed since [2eec7d8](https://github.com/CLARIAH/scholarly-web-annotation-client/commit/d0d1ace2f9dffa82fdda89dc9479ee8987deda80#diff-04c6e90faac2675aa89e2176d2eec7d8).
